LoadConfig:
#  please update the rpcUrl to be your available rpc url before running load test
  rpcUrl:
    - http://127.0.0.1:8121
    - http://127.0.0.1:8122
    - http://127.0.0.1:8123
    - http://127.0.0.1:8124
    - http://127.0.0.1:8125
# minerLockHash is optional which can be empty(''), but (minerBinaryHash | minerArgs) is required
# below is set bob as miner
  minerPrivateKey: '5c2514fb16b83259d3326a0acf05901c15a87dc46239b77b0a501cd58198dca0'
  minerLockHash: ''
  minerCodeHash: '0x94334bdda40b69bae067d84937aa6bbccf8acd0df6626d4b9ac70d4612a11933'
  minerArgs: '0x7f52f0fccdd1d11391c441adfb174f87bca612b0'
  aliceCodeHash: '0x94334bdda40b69bae067d84937aa6bbccf8acd0df6626d4b9ac70d4612a11933'
  aliceArgs: '0x3f1573b44218d4c12a91919a58a863be415a2bc3'

# update withoutVeriTXsNumber value as you want for number of sending txs without verification;
# note: it's better to set the number to be divisible by the cell capacity, e.g. 5/10/50(which can be divided by 50000) etc.
  withoutVeriTXsNumber: 5

# liveCellsNumber: get the number of live cells to send different positive txs with verification
  liveCellsNumber: 2
#  Parameters ：
# xxxInvocationCount: run times of this kind of cases
# xxxThreadPoolSize: size of thread pool
  positiveInvocationCount: 1
  positiveThreadPoolSize: 1

  negativeBlankInvocationCount: 1
  negativeBlankThreadPoolSize: 1

  negativeOverflowInvocationCount: 1
  negativeOverflowThreadPoolSize: 1

  negativeDeadPreviousInvocationCount: 1
  negativeDeadPreviousThreadPoolSize: 1

